spring.application.name=MDAI-Proyecto
spring.datasource.url=jdbc:mysql://localhost:3307/mdai_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=mdai_user
spring.datasource.password=mdai_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8084

# Multipart upload limits: no limit (-1 => unlimited)
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
spring.servlet.multipart.enabled=true
# Tomcat swallow size unlimited
server.tomcat.max-swallow-size=-1
